name: Continuous Integration

# This specifies when the actions will run. 
on:
  push:
    branches: [ main ]  # Trigger on push to main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Specifies the OS of the machine to run on

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Sets up Node.js version 16

    - name: Install dependencies
      run: |
        cd backend
        npm install
        cd ../frontend
        npm install

    - name: Run backend tests
      run: |
        cd backend
        npm test  # Adjust this command based on your test script

    - name: Run frontend tests
      run: |
        cd frontend
        npm test  # Adjust this command based on your test script
